import matplotlib.pyplot as plt
import pandas as pd

# Intention:
# To make charts from CSV generated by stress test


# Read the CSV file
df = pd.read_csv("output.csv", delimiter=";")  # Replace with your CSV file path

# Get column names from the header
columns = df.columns

# Ensure there are exactly 6 columns
if len(columns) != 6:
    raise ValueError("CSV must have 6 columns")

# Create figure with two subplots
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 8))

# Line plot for the first five columns
for i in range(5):
    ax1.plot(df.index, df[columns[i]], label=columns[i])
ax1.set_title("Benchmark Statistic")
ax1.set_xlabel("Request Timeline")
ax1.set_ylabel("Duration (sec)")
ax1.legend(loc="upper left")
# Remove x-axis padding
ax1.set_xlim(df.index.min(), df.index.max())

# Line plot for the sixth column (status code)
ax2.plot(df.index, df[columns[5]], label=columns[5])
ax2.set_title("Response Status")
ax2.set_xlabel("Request Timeline")
ax2.set_ylabel("Status Code")
ax2.legend(loc="upper left")
# Set y-axis to common HTTP status codes
common_http_codes = [200, 400, 500]
ax2.set_yticks(common_http_codes)
# Remove x-axis padding
ax2.set_xlim(df.index.min(), df.index.max())
# Keep your y-axis limit
ax2.set_ylim(150, 550)

# Adjust layout to prevent overlap
plt.tight_layout()

# Show plots
plt.show()
